Test registration
peka80/cypress-reg pull request #1
Opened 2021-12-14 11:32 UTC by peka80

Podigao sam na git test registration page-a. Sa test case-evima.

2021-12-14 15:55 UTC, FilipNedovic requested changes
Ostavio sam ti par manjih komentara, sintaksa je u redu samo da se ocisti malo kod. Sve u svemu, dobro uradjeno skroz.

2021-12-14 15:55 UTC, FilipNedovic commented on cypress/integration/reg.spec.js
> +});
Ovde ostavi praznan red na kraju fajla.

2021-12-14 15:55 UTC, FilipNedovic commented on cypress/integration/reg.spec.js
> +    cy.get('[type="checkbox"]').click();
Okej je ostavljati komentare vezane za kod koji ce biti od pomoci nekom ko ce mozda posle nas raditi na tome, ali zakomentarisan kod ne bi trebao da se dize na git.
Isto vazi i za `xit` i `.only`.

2021-12-15 00:05 UTC, merged

2021-12-15 00:06 UTC, peka80 commented
Da li sam trebao ponov zatražiti review nakon ispravki u kodu?